name: shared_demo
description: A new Flutter template.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1 # Add a gap between widgets regardless of direction (vertical/horizontal).
  ui_shared:
    path: ../../ui_shared_flutter

# dart run build_runner build -d
dev_dependencies:
  build_runner: ^2.4.8 # provides a concrete way of generating files using Dart code
  flutter_gen_runner: ^5.4.0 # The Flutter code generator for your assets, fonts, colors
  flutter_launcher_icons: ^0.13.1 # A command-line tool that simplifies updating Flutter app's launcher icon
  flutter_lints: ^4.0.0
  flutter_test: # Testing library for flutter, built on top of package:test.
    sdk: flutter

# Element of flutter_launcher_icons https://pub.dev/packages/flutter_launcher_icons
# '% dart run flutter_launcher_icons'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/share1024x1024.png"
  macos:
    generate: true
    image_path: "assets/images/share1024x1024.png"
  web:
    generate: true
    image_path: "assets/images/share1024x1024.png"
  windows:
    generate: true
    image_path: "assets/images/share1024x1024.png"

# Element of flutter_gen https://pub.dev/packages/flutter_gen/install
# '% dart pub global activate flutter_gen'
# '% fluttergen'
flutter_gen:
  line_length: 132

flutter:
  uses-material-design: true
  assets:
    - assets/images/
